const INCREMENT = 'INCREMENT';
const DECREMENT = 'DECREMENT';
const TOGGLE_THEME = 'TOGGLE_THEME';
const LOG = 'LOG';
const MIDDLEWARE_LOG = 'MIDDLEWARE_LOG';

export { INCREMENT, DECREMENT, TOGGLE_THEME, MIDDLEWARE_LOG, LOG };
